### ISSUE TITLE
May want to add a unittest hook that doesn't install DA dependencies

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/ALActions#4]
It's nice to have this all documented in one place. For FormFyxer though, the unittests take longer than they should because we add a lot of DA-specific packages that aren't needed. Worth adding it here? Alternative is to use a different off the shelf hook for FormFyxer and similar packages.

**Comment by BryceStevenWilley** [comment]
I can't see the logs from when this issue was made, but I don't think that we ever specifically depended on docassemble dependencies; it's always just used what's listed in your `requirements.txt` and `setup.py`. The latest runs of [FormFyxer tests](https://github.com/SuffolkLITLab/FormFyxer/actions/runs/5892960637/job/15983424981) don't install any docassemble things. It still takes a while, current breakdown is:

* ~40 seconds for Ubuntu updates, checking out the repo, and installing python
* ~1:30 for installing python dependencies
* ~30 seconds for mypy and tests

But I don't see any easy way to improve it more, so I'm gonna close this.
